import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import {
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { HabitsProvider } from "@/providers/HabitsProvider";
import { ClerkProvider } from "@clerk/nextjs";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <NuqsAdapter>
            <HabitsProvider>
              <SidebarProvider>
                <AppSidebar />
                <main className="flex w-full flex-1 relative">
                  {/* <Sidebar /> */}
                  <SidebarTrigger className="sticky  top-0 left-0 z-[10] border-r-1 size-9 cursor-pointer" />
                  <React.Suspense fallback={<div>Loading...</div>}>
                    <div className="w-full">{children}</div>
                  </React.Suspense>
                </main>
              </SidebarProvider>
            </HabitsProvider>
          </NuqsAdapter>
        </body>
      </html>
    </ClerkProvider>
  );
}
